version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet

    working_directory: /CircleCITest

    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
