version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet

    working_directory: ~/CircleCITest

    steps:
      - checkout

      - run:
          name: Dotnet Info
          command: dotnet --info

      - run:
          name: Running xUnit tests
          command: dotnet test CirclCITest.Tests

      #- run:
          #name: Create docker image 
          #command: could use a .bat file here or something...

      #- run: 
          #name: publish to integration environment
          #command:  xcopy or clone or something