version: 2
jobs:
  build:
    docker:
      - image: circleci/microsoft/dotnet:2.1-sdk-nanoserver-1803
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
